[
    {
      pageNumber: 1,
      top: 7.79998779296875,
      left: 14,
      width: 254.87994384765625,
      height: 12.4000244140625
    }
  ],
  [
    {
      pageNumber: 1,
      top: 533.469970703125,
      left: 117.62000274658203,
      width: 89.99999237060547,
      height: 16
    }
  ],
  [
    {
      pageNumber: 1,
      top: 527.469970703125,
      left: 297.6400146484375,
      width: 212.16000366210938,
      height: 23
    }
  ]




  fields: [
    {
      backgroundColor: '#ffffff',
      borderColor: '',
      borderStyle: 'SOLID',
      borderWidth: 1,
      displayLabel: '',
      visible: true,
      inputType: 'TEXT_FIELD',
      tooltip: '',
      fontColor: '',
      fontName: 'Helvetica',
      fontSize: 8,
      alignment: 'LEFT',
      displayFormat: '',
      displayFormatType: 'DEFAULT',
      masked: false,
      maskingText: '*',
      radioCheckType: 'CIRCLE',
      conditionalAction: [Object],
      contentType: 'DATA',
      defaultValue: 'DocuSign Envelope ID: 513233CA-C72B-40F8-B734-3D2DA6742CD2',
      readOnly: false,
      valueExpression: '',
      calculated: false,
      urlOverridable: false,
      required: false,
      minLength: -1,
      maxLength: -1,
      minValue: -1,
      maxValue: -1,
      validationErrMsg: '',
      validation: 'NONE',
      currency: '',
      origin: 'IMPORTED',
      signerIndex: -1,
      name: 'EnvelopeID_1f940507-2a5b-4ff2-b14c-e774b6708767',
      locations: [Array]
    },
    {
      backgroundColor: '',
      borderColor: '',
      borderStyle: 'SOLID',
      borderWidth: -1,
      displayLabel: '',
      visible: true,
      inputType: 'TEXT_FIELD',
      tooltip: '',
      fontColor: '',
      fontName: '',
      fontSize: -1,
      alignment: 'LEFT',
      displayFormat: '',
      displayFormatType: 'DATE',
      masked: false,
      maskingText: '*',
      radioCheckType: 'CIRCLE',
      conditionalAction: [Object],
      contentType: 'SIGNATURE_DATE',
      defaultValue: '',
      readOnly: true,
      valueExpression: '',
      calculated: false,
      urlOverridable: false,
      required: false,
      minLength: -1,
      maxLength: -1,
      minValue: -1,
      maxValue: -1,
      validationErrMsg: '',
      validation: 'NONE',
      currency: '',
      origin: 'AUTHORED',
      signerIndex: 0,
      name: 'Date 1',
      locations: [Array],
      assignee: 'CBJCHBCAABAA83ADmOBrgnKAD88i8jmnn9l07L9X2Vnu'
    },
    {
      backgroundColor: '',
      borderColor: '',
      borderStyle: 'SOLID',
      borderWidth: -1,
      displayLabel: '',
      visible: true,
      inputType: 'SIGNATURE',
      tooltip: '',
      fontColor: '',
      fontName: '',
      fontSize: -1,
      alignment: 'LEFT',
      displayFormat: '',
      displayFormatType: 'DEFAULT',
      masked: false,
      maskingText: '*',
      radioCheckType: 'CIRCLE',
      conditionalAction: [Object],
      contentType: 'SIGNATURE',
      defaultValue: '',
      readOnly: false,
      valueExpression: '',
      calculated: false,
      urlOverridable: false,
      required: true,
      minLength: -1,
      maxLength: -1,
      minValue: -1,
      maxValue: -1,
      validationErrMsg: '',
      validation: 'NONE',
      currency: '',
      origin: 'AUTHORED',
      signerIndex: 0,
      name: 'Signature 1',
      locations: [Array],
      assignee: 'CBJCHBCAABAA83ADmOBrgnKAD88i8jmnn9l07L9X2Vnu'
    }
  ]