[
  [
    {
      pageNumber: 1,
      top: 530.469970703125,
      left: 118.22000122070312,
      width: 90,
      height: 16
    }
  ],
  [
    {
      pageNumber: 1,
      top: 526.27001953125,
      left: 316.239990234375,
      width: 212.1600341796875,
      height: 23
    }
  ]
]


fields: [
  {
    backgroundColor: '',
    borderColor: '',
    borderStyle: 'SOLID',
    borderWidth: -1,
    displayLabel: '',
    visible: true,
    inputType: 'TEXT_FIELD',
    tooltip: '',
    fontColor: '',
    fontName: '',
    fontSize: -1,
    alignment: 'LEFT',
    displayFormat: '',
    displayFormatType: 'DATE',
    masked: false,
    maskingText: '*',
    radioCheckType: 'CIRCLE',
    conditionalAction: [Object],
    contentType: 'SIGNATURE_DATE',
    defaultValue: '',
    readOnly: true,
    valueExpression: '',
    calculated: false,
    urlOverridable: false,
    required: false,
    minLength: -1,
    maxLength: -1,
    minValue: -1,
    maxValue: -1,
    validationErrMsg: '',
    validation: 'NONE',
    currency: '',
    origin: 'AUTHORED',
    signerIndex: 0,
    name: 'Date 1',
    locations: [Array],
    assignee: 'CBJCHBCAABAAVFL1xq8gcp5V9-BDpTiUDiKw5HdPavTf'
  },
  {
    backgroundColor: '',
    borderColor: '',
    borderStyle: 'SOLID',
    borderWidth: -1,
    displayLabel: '',
    visible: true,
    inputType: 'SIGNATURE',
    tooltip: '',
    fontColor: '',
    fontName: '',
    fontSize: -1,
    alignment: 'LEFT',
    displayFormat: '',
    displayFormatType: 'DEFAULT',
    masked: false,
    maskingText: '*',
    radioCheckType: 'CIRCLE',
    conditionalAction: [Object],
    contentType: 'SIGNATURE',
    defaultValue: '',
    readOnly: false,
    valueExpression: '',
    calculated: false,
    urlOverridable: false,
    required: true,
    minLength: -1,
    maxLength: -1,
    minValue: -1,
    maxValue: -1,
    validationErrMsg: '',
    validation: 'NONE',
    currency: '',
    origin: 'AUTHORED',
    signerIndex: 0,
    name: 'Signature 1',
    locations: [Array],
    assignee: 'CBJCHBCAABAAVFL1xq8gcp5V9-BDpTiUDiKw5HdPavTf'
  }
]



const formFields = {
  fields: [
    {
      borderStyle: "SOLID",
      borderWidth: -1,
      visible: true,
      inputType: "TEXT_FIELD",
      fontSize: -1,
      alignment: "LEFT",
      displayFormatType: "DATE",
      masked: false,
      maskingText: "*",
      radioCheckType: "CIRCLE",
      contentType: "SIGNATURE_DATE",
      readOnly: true,
      calculated: false,
      urlOverridable: false,
      required: false,
      minLength: -1,
      maxLength: -1,
      minValue: -1,
      maxValue: -1,
      validation: "NONE",
      origin: "AUTHORED",
      signerIndex: 0,
      name: "Date 1",
      locations: [
        {
          pageNumber: 1,
          top: 530.469970703125,
          left: 118.22000122070312,
          width: 90,
          height: 16,
        },
      ],
    },
    {
      visible: true,
      inputType: "SIGNATURE",
      fontSize: -1,
      alignment: "LEFT",
      displayFormatType: "DEFAULT",
      masked: false,
      maskingText: "*",
      radioCheckType: "CIRCLE",
      contentType: "SIGNATURE",
      readOnly: false,
      calculated: false,
      urlOverridable: false,
      required: true,
      minLength: -1,
      maxLength: -1,
      minValue: -1,
      maxValue: -1,
      validation: "NONE",
      origin: "AUTHORED",
      signerIndex: 0,
      name: "Signature 1",
      locations: [
        {
          pageNumber: 1,
          top: 526.27001953125,
          left: 316.239990234375,
          width: 212.1600341796875,
          height: 23,
        },
      ],
    },
  ],
};


